platform :ios, '6.0'
pod 'RestKit', '~> 0.24.0'
pod 'Objective-LevelDB', '~> 2.1.4'
pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'PinYin4Objc', '~> 1.1.1'
pod 'APAddressBook', '~> 0.1.5'
pod 'MBProgressHUD', '~> 0.9'
pod 'MagicPie', '~> 1.0.1'
pod 'FLAnimatedImage', '~> 1.0.7'
